# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.16

    working_directory: /go/src/yunion.io/x/sqlchemy
    steps:
      - checkout
      - run: GO111MODULE=off go get -v -t -d ./...
      - run:
          command: |
            GO111MODULE=off go test -v ./...

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
